### ISSUE TITLE
[Enhancement] ArtAnimation Flexibility

### ISSUE THREAD

**Issue by angelopoole** [chingu-voyages/v33-bears-team-10#44]
Rather than creating 4 different image classes here you can do something like this using nth item

```scss
.myClass img:nth-child(1) { animation-delay: .5s }
.myClass img:nth-child(2) { animation-delay: 1s }
.myClass img:nth-child(3) { animation-delay: 1.5s }
.myClass img:nth-child(4) { animation-delay: 2s }
```

or use the @for ability inside of scss like this  -> 
```scss
@for $i from 1 through 3 {
  ul:nth-child(3n + #{$i}) {
    background-color: lighten($base-color, $i * 5%);
  }
}
```

-> [sass explanation](https://sass-lang.com/documentation/at-rules/control/for)
-> [Stack overflow item on this](https://stackoverflow.com/questions/8294400/css-animations-with-delay-for-each-child-element)

_Originally posted by @angelopoole in https://github.com/chingu-voyages/v33-bears-team-10/pull/42#discussion_r715287635_
